# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -Wextra -std=c11

# Source file
SRC = exercise2q.c

# Executable name
TARGET = main.exe

# Rule to build the executable
$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $@ $(SRC)

# Clean up the executable
clean:
	rm -f $(TARGET)
	rm -f $(TARGET)
